### ISSUE TITLE
Feature request: export to both .geojson and .poly

### ISSUE THREAD

**Issue by morandd** [AndGem/osm_extract_polygon#17]
While it is possible to use other tools (like python2geojson.py) to convert .poly files to .geojson, if it is easy to add that could be a nice feature to add to this tool. Both output formats are useful: .poly for masking with osmium and .geojson for all other uses.

**Comment by AndGem** [comment]
Hi Dan!

Thanks for another good suggestion. I'll look into how complicated it would be to export to geojson (I have never worked with it) but I can't imagine it being very difficult. This could be a good new feature for `0.3`.

**Comment by AndGem** [comment]
Hi @morandd ,

I've just created version `0.3.0`. If you find time, I'd really like to hear some feedback for this version.

Cheers,
Andreas

**Comment by morandd** [comment]
All the latest improvements work like a charm. Thank you so much :)

**Comment by AndGem** [comment]
Awesome. Glad to hear. I've added some more changes in the newest version.
