### ISSUE TITLE
Feature request: clip to bounding .poly

### ISSUE THREAD

**Issue by morandd** [AndGem/osm_extract_polygon#18]
As raised in this issue [https://github.com/AndGem/osm_extract_polygon/issues/9] there is often the case that .pbf file for a given country includes admin_level boundaries from neighboring countries. 

This leads to a case where, for example, the norway.pbf file contains the complete polygon for several Swedish kommunes. If using this tool for multi-country applications we then have a situation where the Swedish kommune is then defined twice: once in Sweden and a second time in Norway. This is an issue when trying to visualize the results, since the two polygons overlap.

A nice feature would be if osm_extract_polygon could also accept a a .poly boundary, and clip all output regions so they fit inside that boundary. 

I have no idea how hard/easy this is to implement. But I thought it's worth at least clearly stating the issue. 

AndGem, thank you for the fast fix on my other Issue. You can reply  to or close these two issues as you see fit. I just wanted to mention these two feature ideas. I think your tool is basically the only tool for extracting .poly files from OSM so it carries a lot of weight :)

**Comment by AndGem** [comment]
> AndGem, thank you for the fast fix on my other Issue. You can reply to or close these two issues as you see fit. I just wanted to mention these two feature ideas. I think your tool is basically the only tool for extracting .poly files from OSM so it carries a lot of weight :)

I appreciate the kind words; I created it just because I was unable to find anything that would suit my needs (and I wanted to learn a bit more Rust).

he approach you propose should actually not be too difficult to implement, but maybe there are some corner cases that are more tricky to handle. I'll think about this suggestion  and maybe this will be targeted in version `0.4`.

**Comment by morandd** [comment]
I've been working with this using node + turfjs, and the clipping approach I suggested above won't work: You end up with small slivers of foreign regions remaining inside the country boundary clip. 

I'm working on another approach where I calculate the centroid of each region and test whether it's inside the national boundary.

For that - it will be quite nice if/when this utility can simultaneously output GeoJSON and .poly files. The .poly are useful for working with actual OSM data, while the GeoJSON are useful for visualization and for this step of removing foreign regions from a country. When it's done I'll post my node script here for others to use as well.

But this Issue is a dead-end idea so I'll close it soon.

**Comment by morandd** [comment]
Here is a nodejs script using TurfJS library to create a blacklist/whitelist of region names whose centroids fall inside a given national boundary.

This script generates a whitelist/blacklist list of region names, e.g. for Norway at admin_level=4, like this:
` 
+.  Viken.geojson
-    Murmansk.geojson
`

Here's the script. Requires nodejs TurfJS . You will need to edit this script to match how you've layed out the output .poly files:

`
'use strict';

const turf = require('@turf/turf');
const fs = require('fs');
const path = require('path');

const countries = ["norway","sweden"];
const lvls = Array(10).fill().map((_,idx)=>idx); // So we can iterate over the various admin_level values

countries.forEach(coname => {

	// Here we load in the national borders for this country
	// One way to get national border .geoJSON is like this:
	//   wget http://download.geofabrik.de/europe/norway.poly -o norway.poly
	// Then use "polygon2geojson.py" to convert to a GeoJSON file:
	//   python polygon2geojson.py norway.poly
	if (!fs.existsSync('data/'+coname+'.geojson')) return;
	let tmp = fs.readFileSync('data/'+coname+'.geojson');
	if (tmp.length==0) return;
	let national = JSON.parse(tmp);

	// Visit each of the different admin_level heirarchies:
	lvls.forEach(lvl => {
			// Here we expect to find a folder containing files like:
			//  data/norway-latest.osm.pbf_polygons/4/boundaries/Oslo.geojson
			// These were generated using https://github.com/AndGem/osm_extract_polygon
			// and polygon2geojson.py

			fs.readdir('data/'+coname+'-latest.osm.pbf_polygons/' + lvl + '/boundaries', function (err, files) {
				if (err) return;

				// We'll create a blacklist/whitelist file
				// The 'blacklistWhitelist' array will have entries like
				//   ["+	DomesticKommune1.geojson","-	ForeignRegion1.geojson",null]
				// where the tab-delimited "+" prefix means the region *is* part of the country,
				// the "-" prefix means it's not part of the country
				// and null means ignore this entry
				let blacklistWhitelist = files.map( async fn => {

					if (!(fn.indexOf(".geojson")>0)) return null;
					let fullfn = coname+'-latest.osm.pbf_polygons/'+lvl+'/boundaries/'+fn;

					try {
						var reg = JSON.parse(fs.readFileSync(fullfn));
						if ("[Sample region name for debugging.geojson]" == fn){
							console.log(fullfn);
							// These three points can be meaingfully different:
							console.log(turf.centroid(reg));
							console.log(turf.center(reg));
							console.log(turf.centerOfMass(reg));
						}
						if (reg.type=='FeatureCollection') reg = turf.combine(reg);
						let centroidInside =  turf.booleanContains(national.features ? national.features[0] : national, turf.centroid(reg));
						let centerInside =  turf.booleanContains(national.features ? national.features[0] : national, turf.center(reg));
						let centerOfMassInside =  turf.booleanContains(national.features ? national.features[0] : national, turf.centerOfMass(reg));

						if (centroidInside && centerInside && centerOfMassInside){
							//console.log('Yes, ' + coname +' contains ' + fn);
							return "+\t" + fn;
						} else {
							//console.log('*** NOPE*** The region ' + fn +' is not part of ' + coname);
							return "-\t" + fn;
						}
					} catch (ex) {
						console.log("Error while parsing \""+fullfn +"\"");
						console.log(ex);
						console.log(ex.message);
						return null;
					}
					}); // readdir() function for this country/lvl


				// At this point we have a bunch of worker threads doing the centroid coputations
				//   ...waiting....
				// we wait for those to complete using Promise.all()...

				// Wait for al the above logic to complete then write the whitelist file as
				//   data/norway-latest.osm.pbf_polygons/4/autogenerated_blacklistWhitelist.txt

				Promise.all(blacklistWhitelist).then( vals => {
					vals = vals.filter(el => el!=null); // Remove all null entries (corresponding to *.poly files and any other non-geojson files)
					vals = vals.join('\n');
					fs.writeFileSync('data/'+coname+'-latest.osm.pbf_polygons/' + lvl + '/autogenerated_blacklistWhitelist.txt', vals);
				});

/* 
   autogenerated_blacklistWhitelist.txt for Norway admin_level=4
------------
+	Agder.geojson
-	Dalarnas län.geojson
+	Innlandet.geojson
+	Jan Mayen.geojson
-	Jämtlands län.geojson
+	Møre og Romsdal.geojson
+	Nordland.geojson
-	Norrbottens län.geojson
+	Oslo.geojson
+	Rogaland.geojson
+	Svalbard.geojson
+	Troms og Finnmark.geojson
+	Trøndelag.geojson
+	Vestfold og Telemark.geojson
+	Vestland.geojson
+	Viken.geojson
-	Värmlands län.geojson
-	Västerbottens län.geojson
-	Västra Götalands län.geojson
-	Мурманская область.geojson
-----------
Now you can use this tab-delimited file elsewhere in your code to ignore foreign region names.
*/

	}); // Foreach admin level

});// Foreach country
`

**Comment by AndGem** [comment]
Thanks a lot for this. I'll take a look to better understand it. Then I can try to integrate this directly into the tool.

**Comment by morandd** [comment]
There is no trivial solution.

The OSM regions do not contain metadata as to which country they belong to.
The region boundaries are not precise, so clipping using national boundaries could result in small slices of foreign regions being included in the country.

What I have done is use the turf.js library and test each region to ensure: the region centroid is inside the national polygon AND the region center of mass is inside the national polygon AND >95% of the region's area is inside the country (tested as: area(intersection(region,country))/area(region)>0.95). If any one of these tests is false, the region is rejected as belonging to a different country.

This seems too much to add to this utility. Therefore, leaving this note and closing this issue.
