### ISSUE TITLE
`smartstring-0.2.10/src/inline.rs:41:9: assertion failed: len <= MAX_INLINE` on master

### ISSUE THREAD

**Issue by MrFoxPro** [AndGem/osm_extract_polygon#42]

**Comment by AndGem** [comment]
@MrFoxPro I've just updated the depdencies. Maybe this already fixes your issue? Otherwise it would be great if you can provide an example input where the program fails.

**Comment by MrFoxPro** [comment]
> @MrFoxPro I've just updated the depdencies. Maybe this already fixes your issue? Otherwise it would be great if you can provide an example input where the program fails.

Yes I updated deps and it's working now
