### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by corop** [AndGem/osm_extract_polygon#45]
╰─$ ./osm_extract_polygon -f kazakhstan-latest.osm.pbf   
error: cannot set both -o (--overwrite) and -s (--skip)!

**Comment by AndGem** [comment]
uff. sorry.. I must have broken the recent build. Will fix asap.

**Comment by AndGem** [comment]
Hey @corop ,

can you try the new release https://github.com/AndGem/osm_extract_polygon/releases/tag/v.0.5.5 ? 

I think this fixes the issue you have reported. Many thanks for pointing this out.

**Comment by corop** [comment]
> Hey @corop ,
> 
> can you try the new release https://github.com/AndGem/osm_extract_polygon/releases/tag/v.0.5.5 ?
> 
> I think this fixes the issue you have reported. Many thanks for pointing this out.

my test 0.0.5 version ((( need check again.... i5, Debian 12, zsh

-rw-r--r-- 1 asergeev asergeev  34M Jun  5 02:26 china-latest-admin.osm.pbf
-rwxr-xr-x 1 asergeev docker   2.5M Jun  6 23:39 osm_extract_polygon
-rw-r--r-- 1 asergeev docker   6.2K Jun  5 08:40 README.md

╭─asergeev@uran ~/work/osm/country-borders/china 
╰─$ ./osm_extract_polygon --file china-latest-admin.osm.pbf

error: cannot set both -o (--overwrite) and -s (--skip)!

**Comment by AndGem** [comment]
Hey @corop ,

thanks for the update. I understand that you want to check again? 

Either 0.5.5 or the newest 0.5.6 should both work. Please let me know if there is an issue, and ideally with a pbf file (or a link where I can download it from) to try it out.

**Comment by AndGem** [comment]
i assume everything is fine now
