### ISSUE TITLE
Provide relation id in geojson file

### ISSUE THREAD

**Issue by Gared** [AndGem/osm_extract_polygon#48]
First of all thanks for this super useful tool!

I would like to generate geojson files, but need to get the relation to osm data and for that it would be helpful to have the relation-id in the geojson file. 
Would that be doable?

**Comment by AndGem** [comment]
Hey @Gared ,

thanks for the issue and the kind words.

I took a brief look today in the morning and I think it is an easy change. Can you check this version? https://github.com/AndGem/osm_extract_polygon/releases/tag/v.0.5.7

It creates a property map like this: 
```
"properties":{"admin_level":8,"name":"Papaichton","relation_id":1663801}
```

Let me know if this works for you.

**Comment by Gared** [comment]
@AndGem LGTM! Thank you for your fast changes!
